# Generated by Django 2.2 on 2022-09-09 12:22

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import smart_selects.db_fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=250)),
                ('message', models.TextField()),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'SMS Notification',
                'verbose_name_plural': 'SMS Notifications',
            },
        ),
        migrations.CreateModel(
            name='otpModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
                ('tim', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='serviceStatusTypeModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Service Status Type',
                'verbose_name_plural': 'Service Status Type',
            },
        ),
        migrations.CreateModel(
            name='sessionModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
                ('tim', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='settingsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sms_token', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Settings',
                'verbose_name_plural': 'Settings',
            },
        ),
        migrations.CreateModel(
            name='userModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=255)),
                ('lastName', models.CharField(max_length=255)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(max_length=255)),
                ('passw', models.CharField(max_length=255)),
                ('gender', models.CharField(blank=True, choices=[('male', 'male'), ('female', 'female'), ('others', 'others')], default='', max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='userimages/')),
                ('phoneStatus', models.BooleanField(default=False)),
                ('dateOfRegistration', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
        ),
        migrations.CreateModel(
            name='userTypeModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'User Type',
                'verbose_name_plural': 'User Type',
            },
        ),
        migrations.CreateModel(
            name='vehicleTypeModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Vehicle Type',
                'verbose_name_plural': 'Vehicle Type',
            },
        ),
        migrations.CreateModel(
            name='vehicleModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=255)),
                ('model', models.CharField(max_length=255)),
                ('color', models.CharField(max_length=255)),
                ('licensePlateNumber', models.CharField(max_length=255)),
                ('blueBookPhoto', models.ImageField(blank=True, null=True, upload_to='bluebook/')),
                ('blueBookRenewalDate', models.DateField(blank=True, null=True)),
                ('blueBookExpiryDate', models.DateField(blank=True, null=True)),
                ('blueBookOwnerName', models.CharField(max_length=255)),
                ('user', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_user', to='api.userModel')),
                ('vehicleType', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_vehicleType', to='api.vehicleTypeModel')),
            ],
            options={
                'verbose_name': 'Vehicle',
                'verbose_name_plural': 'Vehicles',
            },
        ),
        migrations.CreateModel(
            name='serviceLogModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dropLocation', models.CharField(default='', max_length=255)),
                ('pickUpLocation', models.CharField(default='', max_length=255)),
                ('deleteStatus', models.BooleanField(default=False)),
                ('invoice', models.FileField(blank=True, null=True, upload_to='invoices/')),
                ('dateOfMaintanance', models.DateTimeField(blank=True, null=True)),
                ('statusType', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_type', to='api.serviceStatusTypeModel')),
                ('user', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='vehicle', chained_model_field='vehicle', default='', on_delete=django.db.models.deletion.CASCADE, related_name='user_vehicle', show_all=True, to='api.vehicleModel')),
                ('user1', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='user_vehicle', to='api.userModel')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_vehicle', to='api.vehicleModel')),
            ],
            options={
                'verbose_name': 'Service Record',
                'verbose_name_plural': 'Service Records',
            },
        ),
        migrations.CreateModel(
            name='notificationLogModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('file', models.FileField(blank=True, null=True, upload_to='notificationfiles/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notif_user', to='api.userModel')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
            },
        ),
        migrations.CreateModel(
            name='addressModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
                ('province', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('address', models.CharField(default='', max_length=255)),
                ('deleteStatus', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='address_user', to='api.userModel')),
            ],
            options={
                'verbose_name': 'Address',
                'verbose_name_plural': 'Addresses',
            },
        ),
    ]
