# Generated by Django 4.0.4 on 2022-05-23 06:08

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='addressModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('province', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('deleteStatus', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='otpModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
                ('tim', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='serviceStatusTypeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='sessionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
                ('tim', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='userModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=255)),
                ('lastName', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
                ('passw', models.CharField(max_length=255)),
                ('gender', models.CharField(max_length=255)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='userimages/')),
                ('deviceId', models.IntegerField(blank=True, null=True)),
                ('phoneStatus', models.BooleanField(default=False)),
                ('dateOfRegistration', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('address', models.ManyToManyField(blank=True, related_name='user_address', to='api.addressmodel')),
            ],
        ),
        migrations.CreateModel(
            name='userTypeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='vehicleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=255)),
                ('model', models.CharField(max_length=255)),
                ('color', models.CharField(max_length=255)),
                ('licensePlateNumber', models.CharField(max_length=255)),
                ('blueBookPhoto', models.ImageField(blank=True, null=True, upload_to='bluebook/')),
                ('blueBookRenewalDate', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('blueBookExpiryDate', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('blueBookOwnerName', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_user', to='api.usermodel')),
            ],
        ),
        migrations.AddField(
            model_name='usermodel',
            name='userType',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_userType', to='api.usertypemodel'),
        ),
        migrations.CreateModel(
            name='serviceLogModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleteStatus', models.BooleanField(default=False)),
                ('invoice', models.FileField(blank=True, null=True, upload_to='invoices/')),
                ('dateOfMaintanance', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_address', to='api.addressmodel')),
                ('statusType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_type', to='api.servicestatustypemodel')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_vehicle', to='api.vehiclemodel')),
            ],
        ),
        migrations.CreateModel(
            name='notificationLogModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('file', models.FileField(blank=True, null=True, upload_to='notificationfiles/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notif_user', to='api.usermodel')),
            ],
        ),
        migrations.AddField(
            model_name='addressmodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='address_user', to='api.usermodel'),
        ),
    ]
