# Generated by Django 2.2 on 2022-09-09 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicelogmodel',
            name='user1',
        ),
    ]
