# Generated by Django 2.2 on 2022-09-09 12:31

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_servicelogmodel_user1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicelogmodel',
            name='user',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='vehicle', chained_model_field='vehicle', default='', on_delete=django.db.models.deletion.CASCADE, related_name='user_vehicle', show_all=True, to='api.userModel'),
        ),
    ]
