# Generated by Django 2.2 on 2022-09-09 12:33

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20220909_1816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicelogmodel',
            name='user',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='vehicleModel', chained_model_field='vehicleModel', on_delete=django.db.models.deletion.CASCADE, related_name='user_vehicle', show_all=True, to='api.userModel'),
        ),
    ]
