# Generated by Django 2.2 on 2022-09-09 12:38

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20220909_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicelogmodel',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='user_vehicle', to='api.userModel'),
        ),
        migrations.AlterField(
            model_name='servicelogmodel',
            name='vehicle',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='user', chained_model_field='user', on_delete=django.db.models.deletion.CASCADE, show_all=True, to='api.vehicleModel'),
        ),
    ]
