# Generated by Django 4.0.4 on 2022-05-24 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_servicelogmodel_dateofmaintanance_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='settingsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sms_token', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Settings',
                'verbose_name_plural': 'Settings',
            },
        ),
        migrations.CreateModel(
            name='vehicleTypeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Vehicle Type',
                'verbose_name_plural': 'Vehicle Type',
            },
        ),
        migrations.AlterModelOptions(
            name='addressmodel',
            options={'verbose_name': 'Address', 'verbose_name_plural': 'Addresses'},
        ),
        migrations.AlterModelOptions(
            name='notificationlogmodel',
            options={'verbose_name': 'Notification', 'verbose_name_plural': 'Notifications'},
        ),
        migrations.AlterModelOptions(
            name='servicelogmodel',
            options={'verbose_name': 'Service Log', 'verbose_name_plural': 'Service Logs'},
        ),
        migrations.AlterModelOptions(
            name='servicestatustypemodel',
            options={'verbose_name': 'Service Status Type', 'verbose_name_plural': 'Service Status Type'},
        ),
        migrations.AlterModelOptions(
            name='usermodel',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AlterModelOptions(
            name='usertypemodel',
            options={'verbose_name': 'User Type', 'verbose_name_plural': 'User Type'},
        ),
        migrations.AlterModelOptions(
            name='vehiclemodel',
            options={'verbose_name': 'Vehicle', 'verbose_name_plural': 'Vehicles'},
        ),
        migrations.AddField(
            model_name='vehiclemodel',
            name='vehicleType',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_vehicleType', to='api.vehicletypemodel'),
        ),
    ]
