# Generated by Django 4.0.4 on 2022-05-26 06:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_settingsmodel_vehicletypemodel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicelogmodel',
            name='statusType',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_type', to='api.servicestatustypemodel'),
        ),
    ]
