# Generated by Django 2.2 on 2022-09-09 12:45

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20220909_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicelogmodel',
            name='vehicle',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='user', chained_model_field='user', on_delete=django.db.models.deletion.CASCADE, to='api.vehicleModel'),
        ),
    ]
