# Generated by Django 4.0.4 on 2022-05-29 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_addressmodel_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='addressmodel',
            name='dropLocation',
            field=models.CharField(default='drop', max_length=255),
            preserve_default=False,
        ),
    ]
