# Generated by Django 4.0.4 on 2022-06-01 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_servicelogmodel_statustype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addressmodel',
            name='dropLocation',
        ),
        migrations.AddField(
            model_name='servicelogmodel',
            name='dropLocation',
            field=models.CharField(default='a', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='servicelogmodel',
            name='pickUpLocation',
            field=models.CharField(default='a', max_length=255),
            preserve_default=False,
        ),
    ]
