# Generated by Django 4.0.4 on 2022-06-08 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_remove_servicelogmodel_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicelogmodel',
            name='dateOfMaintanance',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
