# Generated by Django 4.0.4 on 2022-06-10 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_notificationmodel_alter_servicelogmodel_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notificationmodel',
            old_name='number',
            new_name='phone',
        ),
        migrations.RemoveField(
            model_name='notificationmodel',
            name='name',
        ),
    ]
