# Generated by Django 4.0.4 on 2022-06-10 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_rename_number_notificationmodel_phone_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehiclemodel',
            name='user',
        ),
    ]
