# Generated by Django 4.0.4 on 2022-06-10 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_remove_vehiclemodel_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notificationmodel',
            options={'verbose_name': 'SMS Notification', 'verbose_name_plural': 'SMS Notifications'},
        ),
    ]
