# Generated by Django 4.0.4 on 2022-06-10 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_notificationmodel_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationmodel',
            name='phone',
            field=models.CharField(max_length=250),
        ),
    ]
