# Generated by Django 4.0.4 on 2022-06-10 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_notificationmodel_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicelogmodel',
            name='user',
        ),
        migrations.AddField(
            model_name='vehiclemodel',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_user', to='api.usermodel'),
            preserve_default=False,
        ),
    ]
