# Generated by Django 2.2 on 2022-08-31 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_auto_20220829_2023'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usermodel',
            old_name='photo',
            new_name='image',
        ),
    ]
