# Generated by Django 2.2 on 2022-08-31 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_auto_20220831_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='image',
            field=models.ImageField(blank=True, default='media/userimages/R.png', upload_to='userimages/'),
        ),
    ]
