# Generated by Django 2.2 on 2022-08-31 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_auto_20220831_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='passw',
            field=models.CharField(max_length=32),
        ),
    ]
