# Generated by Django 2.2 on 2022-09-01 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_auto_20220831_1901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='passw',
            field=models.CharField(max_length=255),
        ),
    ]
